name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: front

      - name: Run lint
        run: npm run lint
        working-directory: front

      - name: Run Cypress e2e tests
        run: npm run e2e:ci
        working-directory: front

      - name: Generate coverage report
        run: npm run e2e:coverage
        working-directory: front

      - name: Upload lcov-report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: front/coverage/lcov-report

