name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run test:ci

      - name: Build application
        run: npm run build

      - name: Run Cypress end-to-end tests
        run: npm run e2e:ci

      - name: Generate Cypress coverage report
        run: npm run e2e:coverage

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: ./coverage/lcov-report
